import { ArrowDown, ArrowUp, Copy, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import Badge from "../ui/Badge";
import { Button, IconButton } from "../ui/Button";

function name(items, id) { return items.find((item) => item.id === id)?.name || "—"; }
export default function HandoverCard({ note, index, count, drivers, vehicles, issues = [], onEdit, onMove, onDuplicate, onDelete }) {
  const [expanded, setExpanded] = useState(false);
  return <article className="ts-card overflow-hidden"><div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><span className="font-mono font-semibold">{note.time || "—"}</span><button type="button" aria-expanded={expanded} aria-controls={`handover-${note.id}`} onClick={() => setExpanded((value) => !value)} className="min-w-0 flex-1 text-left"><span className="block font-semibold">{name(vehicles, note.vehicleId)} · {name(drivers, note.fromDriverId)} → {name(drivers, note.toDriverId)}</span><span className="block truncate text-sm text-[var(--ts-text-muted)]">{note.location || "No location"}</span></button><div className="flex gap-1">{issues.some((issue) => issue.severity === "error") ? <Badge tone="danger">Conflict</Badge> : null}<IconButton label="Move handover up" onClick={() => onMove(note.id, "up")} disabled={index === 0}><ArrowUp className="h-4 w-4" /></IconButton><IconButton label="Move handover down" onClick={() => onMove(note.id, "down")} disabled={index === count - 1}><ArrowDown className="h-4 w-4" /></IconButton></div></div>{expanded ? <div id={`handover-${note.id}`} className="border-t border-[var(--ts-border)] bg-[var(--ts-surface-muted)] p-4 text-sm"><div className="grid gap-3 sm:grid-cols-2"><p><strong>Instruction:</strong> {note.instruction || "—"}</p><p><strong>Key location:</strong> {note.keyLocation || "—"}</p><p><strong>Visible to:</strong> {note.visibleToDriverIds?.map((id) => name(drivers, id)).join(", ") || "Operational only"}</p><p className="whitespace-pre-line"><strong>Notes:</strong> {note.notes || "—"}</p></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => onEdit(note)}><Pencil className="h-4 w-4" /> Edit</Button><Button onClick={() => onDuplicate(note)}><Copy className="h-4 w-4" /> Duplicate</Button><Button variant="danger" onClick={() => onDelete(note.id)}><Trash2 className="h-4 w-4" /> Delete</Button></div></div> : null}</article>;
}
