import { ArrowDown, ArrowUp, Copy, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import Badge from "../ui/Badge";
import { Button, IconButton } from "../ui/Button";

export default function ImportantInfoCard({ item, index, count, onEdit, onMove, onDuplicate, onDelete }) {
  const [expanded, setExpanded] = useState(false);
  const summary = item.type === "Route" ? [item.from, item.to].filter(Boolean).join(" → ") : item.name || item.address || item.phone || "No summary";
  return <article className="ts-card overflow-hidden"><div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><Badge tone="info">{item.type || "Note"}</Badge><button type="button" aria-expanded={expanded} aria-controls={`info-${item.id}`} onClick={() => setExpanded((value) => !value)} className="min-w-0 flex-1 text-left"><span className="block font-semibold">{item.title || item.name || item.from || "Important information"}</span><span className="block truncate text-sm text-[var(--ts-text-muted)]">{summary}</span></button><div className="flex gap-1"><IconButton label="Move information up" onClick={() => onMove(item.id, "up")} disabled={index === 0}><ArrowUp className="h-4 w-4" /></IconButton><IconButton label="Move information down" onClick={() => onMove(item.id, "down")} disabled={index === count - 1}><ArrowDown className="h-4 w-4" /></IconButton></div></div>{expanded ? <div id={`info-${item.id}`} className="border-t border-[var(--ts-border)] bg-[var(--ts-surface-muted)] p-4 text-sm"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="font-semibold">Route</dt><dd>{[item.from, item.to].filter(Boolean).join(" → ") || "—"}</dd></div><div><dt className="font-semibold">Travel</dt><dd>{[item.distance, item.estimatedTravelTime].filter(Boolean).join(" · ") || "—"}</dd></div><div><dt className="font-semibold">Contact</dt><dd>{[item.name, item.phone, item.email].filter(Boolean).join(" · ") || "—"}</dd></div><div><dt className="font-semibold">Address</dt><dd>{item.address || "—"}</dd></div></dl><p className="mt-3 whitespace-pre-line"><strong>Notes:</strong> {item.notes || "—"}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => onEdit(item)}><Pencil className="h-4 w-4" /> Edit</Button><Button onClick={() => onDuplicate(item)}><Copy className="h-4 w-4" /> Duplicate</Button><Button variant="danger" onClick={() => onDelete(item.id)}><Trash2 className="h-4 w-4" /> Delete</Button></div></div> : null}</article>;
}
