import { useEffect, useState } from "react";
import { duplicateDriver } from "../../domain/resourceMutations";
import { getDriverUsage, totalUsage } from "../../domain/resourceUsage";
import Badge from "../ui/Badge";
import { Button } from "../ui/Button";
import { Input, Select, Textarea } from "../ui/FormControls";

const empty = { id: null, name: "", defaultVehicle: "", isActive: true, phone: "", email: "", notes: "" };
export default function DriverManager({ schedule, onSave, onDelete, onReassign, onDirtyChange }) {
  const [draft, setDraft] = useState(empty);
  const [replacement, setReplacement] = useState("");
  useEffect(() => { onDirtyChange?.(Boolean(draft.id || draft.name || draft.defaultVehicle || draft.phone || draft.email || draft.notes)); }, [draft, onDirtyChange]);
  const set = (field, value) => setDraft((current) => ({ ...current, [field]: value }));
  const save = () => { if (!draft.name.trim()) return; onSave({ ...draft, name: draft.name.trim() }); setDraft(empty); };
  return <div className="space-y-4"><section className="ts-card grid gap-3 p-4 sm:grid-cols-2"><label className="ts-label">Name<Input value={draft.name} maxLength={150} onChange={(event) => set("name", event.target.value)} /></label><label className="ts-label">Default vehicle<Select value={draft.defaultVehicle} onChange={(event) => set("defaultVehicle", event.target.value)}><option value="">None</option>{schedule.vehicles.filter((item) => item.isActive || item.id === draft.defaultVehicle).map((item) => <option key={item.id} value={item.id}>{item.name}{item.isActive ? "" : " — Inactive"}</option>)}</Select></label><label className="ts-label">Phone<Input value={draft.phone} maxLength={100} onChange={(event) => set("phone", event.target.value)} /></label><label className="ts-label">Email<Input type="email" value={draft.email} maxLength={254} onChange={(event) => set("email", event.target.value)} /></label><label className="ts-label sm:col-span-2">Notes<Textarea value={draft.notes} maxLength={10000} onChange={(event) => set("notes", event.target.value)} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.isActive} onChange={(event) => set("isActive", event.target.checked)} />Active driver</label><div className="flex flex-wrap gap-2 sm:justify-end"><Button variant="primary" onClick={save}>{draft.id ? "Update Driver" : "Add Driver"}</Button>{draft.id ? <Button onClick={() => setDraft(empty)}>Cancel</Button> : null}</div></section>
    <div className="grid gap-3">{schedule.drivers.map((driver) => { const usage = getDriverUsage(schedule, driver.id); const referenced = totalUsage(usage); const activeReplacements = schedule.drivers.filter((item) => item.isActive && item.id !== driver.id); return <article key={driver.id} className="ts-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold break-words">{driver.name}</h3><div className="mt-1 flex flex-wrap gap-1"><Badge tone={driver.isActive ? "success" : "neutral"}>{driver.isActive ? "Active" : "Inactive"}</Badge><Badge>{usage.movements} movements</Badge><Badge>{usage.handoverFrom + usage.handoverTo + usage.handoverVisible} handovers</Badge><Badge>{usage.audiences} audience references</Badge></div><p className="mt-2 text-sm text-neutral-600">{driver.phone || driver.email || "No contact details"}</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setDraft(driver)}>Edit</Button><Button onClick={() => onSave(duplicateDriver(driver))}>Duplicate</Button><Button onClick={() => onSave({ ...driver, isActive: !driver.isActive })}>{driver.isActive ? `Deactivate ${driver.name}` : `Activate ${driver.name}`}</Button><Button variant="danger" disabled={referenced > 0} title={referenced ? `Referenced ${referenced} times` : ""} onClick={() => onDelete(driver.id)}>Delete</Button></div></div>{referenced ? <div className="mt-3 ts-alert ts-alert--warning"><p>Deletion blocked: {referenced} schedule references remain. Deactivate or reassign first.</p><div className="mt-2 flex flex-wrap gap-2"><Select value={replacement} onChange={(event) => setReplacement(event.target.value)} aria-label={`Replacement driver for ${driver.name}`}><option value="">Select active replacement…</option>{activeReplacements.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Button disabled={!replacement} onClick={() => onReassign(driver.id, replacement)}>Reassign Driver References</Button></div></div> : null}</article>; })}</div>
  </div>;
}
