import { useEffect, useState } from "react";
import { duplicateVehicle } from "../../domain/resourceMutations";
import { getVehicleUsage, totalUsage } from "../../domain/resourceUsage";
import Badge from "../ui/Badge";
import { Button } from "../ui/Button";
import { Input, Select, Textarea } from "../ui/FormControls";

const empty = { id: null, name: "", registration: "", make: "", model: "", capacity: null, isActive: true, notes: "" };
export default function VehicleManager({ schedule, onSave, onDelete, onReassign, onDirtyChange }) {
  const [draft, setDraft] = useState(empty); const [replacement, setReplacement] = useState(""); const [error, setError] = useState("");
  useEffect(() => { onDirtyChange?.(Boolean(draft.id || draft.name || draft.registration || draft.make || draft.model || draft.capacity || draft.notes)); }, [draft, onDirtyChange]);
  const set = (field, value) => setDraft((current) => ({ ...current, [field]: value }));
  const save = () => { const duplicate = schedule.vehicles.some((item) => item.id !== draft.id && item.registration && draft.registration && item.registration.replace(/[\s-]/g, "").toUpperCase() === draft.registration.replace(/[\s-]/g, "").toUpperCase()); if (duplicate) return setError("Registration is already assigned to another vehicle."); if (!draft.name.trim()) return; onSave({ ...draft, name: draft.name.trim() }); setDraft(empty); setError(""); };
  return <div className="space-y-4"><section className="ts-card grid gap-3 p-4 sm:grid-cols-2"><label className="ts-label">Name<Input value={draft.name} maxLength={150} onChange={(event) => set("name", event.target.value)} /></label><label className="ts-label">Registration<Input value={draft.registration} maxLength={50} onChange={(event) => set("registration", event.target.value)} /></label><label className="ts-label">Make<Input value={draft.make} maxLength={100} onChange={(event) => set("make", event.target.value)} /></label><label className="ts-label">Model<Input value={draft.model} maxLength={100} onChange={(event) => set("model", event.target.value)} /></label><label className="ts-label">Capacity<Input type="number" min="1" max="100" value={draft.capacity ?? ""} onChange={(event) => set("capacity", event.target.value ? Number(event.target.value) : null)} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.isActive} onChange={(event) => set("isActive", event.target.checked)} />Active vehicle</label><label className="ts-label sm:col-span-2">Notes<Textarea value={draft.notes} maxLength={10000} onChange={(event) => set("notes", event.target.value)} /></label>{error ? <p className="ts-field-error sm:col-span-2">{error}</p> : null}<div className="flex flex-wrap gap-2 sm:col-span-2 sm:justify-end"><Button variant="primary" onClick={save}>{draft.id ? "Update Vehicle" : "Add Vehicle"}</Button>{draft.id ? <Button onClick={() => setDraft(empty)}>Cancel</Button> : null}</div></section>
    <div className="grid gap-3">{schedule.vehicles.map((vehicle) => { const usage = getVehicleUsage(schedule, vehicle.id); const referenced = totalUsage(usage); const replacements = schedule.vehicles.filter((item) => item.isActive && item.id !== vehicle.id); return <article key={vehicle.id} className="ts-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold break-words">{vehicle.name}</h3><p className="text-sm text-neutral-600">{[vehicle.registration, vehicle.make, vehicle.model].filter(Boolean).join(" · ") || "No vehicle metadata"}</p><div className="mt-2 flex flex-wrap gap-1"><Badge tone={vehicle.isActive ? "success" : "neutral"}>{vehicle.isActive ? "Active" : "Inactive"}</Badge><Badge>{usage.movements} movements</Badge><Badge>{usage.defaultDrivers} default drivers</Badge><Badge>{usage.handovers} handovers</Badge></div></div><div className="flex flex-wrap gap-2"><Button onClick={() => setDraft(vehicle)}>Edit</Button><Button onClick={() => onSave(duplicateVehicle(vehicle))}>Duplicate</Button><Button onClick={() => onSave({ ...vehicle, isActive: !vehicle.isActive })}>{vehicle.isActive ? `Deactivate ${vehicle.name}` : `Activate ${vehicle.name}`}</Button><Button variant="danger" disabled={referenced > 0} onClick={() => onDelete(vehicle.id)}>Delete</Button></div></div>{referenced ? <div className="mt-3 ts-alert ts-alert--warning"><p>Deletion blocked: {referenced} schedule references remain. Deactivate or reassign first.</p><div className="mt-2 flex flex-wrap gap-2"><Select value={replacement} onChange={(event) => setReplacement(event.target.value)} aria-label={`Replacement vehicle for ${vehicle.name}`}><option value="">Select active replacement…</option>{replacements.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Button disabled={!replacement} onClick={() => onReassign(vehicle.id, replacement)}>Reassign Vehicle References</Button></div></div> : null}</article>; })}</div>
  </div>;
}
