import { describe, expect, it } from "vitest";
import { validState } from "../import/testFixtures";
import { getExportDocument } from "./exportHtml";

describe("original programme print generator", () => {
  it.each(["executive", "executiveCg", "executiveMarida", "operational", "driver", "workingTime", "importantInfo"])("generates the %s programme", (view) => {
    const state = validState();
    const output = getExportDocument(state, view, { selectedDriverId: state.drivers[0].id });
    expect(output.fullHtml).toContain("<!doctype html>");
    expect(output.fullHtml).toContain(output.bodyHtml);
    expect(output.fullHtml).toContain("Generated by ScheduleIt");
  });

  it("retains original one-day-per-page CSS", () => {
    const styles = getExportDocument(validState(), "executive").styles;
    expect(styles).toContain(".executive-day-section:not(.first-day-section)");
    expect(styles).toContain("page-break-before: always");
    expect(styles).not.toContain("print-layout-continuous");
  });

  it("keeps executive pickups safe and operational/driver pickups complete", () => {
    const state = validState();
    state.movements[0].pickups = [{ id: "pickup-1", time: "07:30", location: "Hotel", address: "Pickup address", person: "Ambassador", contactPhone: "+49 123", notes: "Side entrance", sortOrder: 10 }];
    const executive = getExportDocument(state, "executive").fullHtml;
    expect(executive).toContain("Ambassador");
    expect(executive).toContain("Hotel");
    expect(executive).not.toContain("+49 123");
    expect(executive).not.toContain("Side entrance");
    for (const view of ["operational", "driver"]) {
      const html = getExportDocument(state, view, { selectedDriverId: state.movements[0].driverId }).fullHtml;
      expect(html).toContain("Pickup address");
      expect(html).toContain("+49 123");
      expect(html).toContain("Side entrance");
    }
  });
});
